### ISSUE TITLE
Error using options Fields to include

### ISSUE THREAD

**Issue by kittiu** [digital-boss/n8n-nodes-odoo#1]
Hi, thanks for making this plugin. I tested working well, except when I try to scope only some fields, got following error.

I am not sure how to use Fields to include. I have tried many ways, ["id", "price"] and etc...

![image](https://user-images.githubusercontent.com/1973598/163423445-c160bd8a-80ea-4d5c-9f07-cd54536bb246.png)

What is the right way to use Fields to include?

**Comment by feelgood-interface** [comment]
You need to pass in an array when using expressions, e.g. `{{["id"]}}`. The load options will be fixed in the next version.

**Comment by feelgood-interface** [comment]
The load options is solved in version 0.3.0.
